import type { Category, Comparison, Tool, Workflow } from "./types";

export const categories = [
  {
    slug: "lead-ops",
    name: "名單與商機整理",
    summary: "把表單、信件、聊天內容整理成可追蹤的商機清單。",
    focus: "適合顧問、接案者、B2B 業務與小型電商。",
    keywords: ["AI 名單整理", "自動化商機", "Gmail Google Sheets n8n"],
  },
  {
    slug: "content-ops",
    name: "內容營運",
    summary: "把靈感、簡報、會議記錄變成發布排程與 SEO 草稿。",
    focus: "適合創作者、行銷團隊與內容型網站經營者。",
    keywords: ["AI 內容流程", "SEO 工作流", "Notion ChatGPT 自動化"],
  },
  {
    slug: "support-ops",
    name: "客服與社群回覆",
    summary: "用 AI 分流重複問題，讓人工只處理高風險訊息。",
    focus: "適合 LINE 官方帳號、社群小編與客服窗口。",
    keywords: ["LINE AI 客服", "自動分類訊息", "客服自動化"],
  },
  {
    slug: "reporting",
    name: "報表與決策",
    summary: "把分散資料整理成每週摘要、異常提醒與下一步建議。",
    focus: "適合營運、主管、自由工作者與專案負責人。",
    keywords: ["AI 報表", "Google Sheets 自動摘要", "營運儀表板"],
  },
] as const satisfies readonly Category[];

export const tools = [
  {
    slug: "n8n",
    name: "n8n",
    category: "automation",
    summary: "可自架也可雲端使用的自動化平台，適合複雜條件、資料轉換與多步驟流程。",
    bestFor: ["需要細緻控制資料流", "想保留自架選項", "流程會越長越複雜"],
    pricingHint: "有雲端方案與自架選項；實際成本取決於執行量與部署方式。",
    officialUrl: "https://n8n.io/",
    alternatives: ["make", "zapier"],
  },
  {
    slug: "make",
    name: "Make",
    category: "automation",
    summary: "視覺化情境流程工具，適合快速串接常見 SaaS 與建立行銷、營運自動化。",
    bestFor: ["偏好視覺化流程圖", "要快速驗證自動化", "行銷與營運工具串接"],
    pricingHint: "通常依操作量與方案計費；適合先用小流程驗證價值。",
    officialUrl: "https://www.make.com/",
    alternatives: ["n8n", "zapier"],
  },
  {
    slug: "zapier",
    name: "Zapier",
    category: "automation",
    summary: "上手快、整合範圍廣的自動化工具，適合簡短、穩定、非工程導向的流程。",
    bestFor: ["非技術使用者", "快速連接主流工具", "步驟較短的流程"],
    pricingHint: "多以任務量與功能層級計費；大量流程前要估算任務成本。",
    officialUrl: "https://zapier.com/",
    alternatives: ["make", "n8n"],
  },
  {
    slug: "chatgpt",
    name: "ChatGPT",
    category: "ai",
    summary: "負責摘要、分類、草稿、檢查清單與下一步建議的 AI 層。",
    bestFor: ["文字摘要", "內容生成", "客服回覆草稿", "分類與標籤"],
    pricingHint: "可手動使用，也可透過 API 或平台整合；v1 先保留手動匯入流程。",
    officialUrl: "https://chatgpt.com/",
    alternatives: ["notion"],
  },
  {
    slug: "google-sheets",
    name: "Google Sheets",
    category: "database",
    summary: "小型 MVP 最容易上線的資料表，適合名單、內容排程與簡易報表。",
    bestFor: ["手動稽核資料", "小團隊共編", "低成本 MVP 資料層"],
    pricingHint: "通常隨 Google 帳號或 Workspace 使用；注意權限與資料量限制。",
    officialUrl: "https://www.google.com/sheets/about/",
    alternatives: ["notion"],
  },
  {
    slug: "gmail",
    name: "Gmail",
    category: "source",
    summary: "常見的商機、客服、發票與合作洽談入口，適合作為自動化觸發來源。",
    bestFor: ["信件分類", "附件整理", "詢問信與合作信追蹤"],
    pricingHint: "個人與 Workspace 皆可用；正式流程需管理 OAuth 權限。",
    officialUrl: "https://www.google.com/gmail/about/",
    alternatives: ["line"],
  },
  {
    slug: "notion",
    name: "Notion",
    category: "workspace",
    summary: "適合收斂 SOP、內容排程、知識庫與人工審核狀態。",
    bestFor: ["內容日曆", "SOP 文件", "人工審核流程"],
    pricingHint: "依工作區方案計費；作為內容中台時要先定義資料庫欄位。",
    officialUrl: "https://www.notion.so/",
    alternatives: ["google-sheets"],
  },
  {
    slug: "line",
    name: "LINE 官方帳號",
    category: "channel",
    summary: "台灣常見客服與社群入口，適合做訊息分流、標籤與人工接手提醒。",
    bestFor: ["即時客服", "會員訊息", "社群導購"],
    pricingHint: "依官方帳號方案與訊息量而定；串接前要確認 API 權限。",
    officialUrl: "https://www.linebiz.com/tw/service/account-solutions/line-official-account/",
    alternatives: ["gmail"],
  },
] as const satisfies readonly Tool[];

export const workflows = [
  {
    slug: "gmail-leads-to-sheets-triage",
    title: "Gmail 詢問信自動整理到 Google Sheets",
    summary: "把合作、詢價、試用申請信件整理成商機表，並用 AI 產生優先級與下一步。",
    category: "lead-ops",
    tools: ["gmail", "google-sheets", "chatgpt", "n8n"],
    difficulty: "beginner",
    estimatedMinutes: 45,
    useCase: "每天收到 5 到 50 封詢問信，但常因漏回、沒有分類或沒有下次追蹤日期而流失商機。",
    steps: [
      {
        title: "建立搜尋條件",
        description: "先用 Gmail 標籤或搜尋條件找出詢價、合作、試用、報價等高意圖信件。",
        tools: ["gmail"],
        qualityGate: "至少抽查 20 封信，確認規則沒有抓到電子報或系統通知。",
      },
      {
        title: "抽取欄位",
        description: "把寄件者、公司、需求、預算線索、截止日期與原始信件連結整理成表格欄位。",
        tools: ["n8n", "google-sheets"],
        qualityGate: "每筆資料都要保留原始信件連結，方便人工回查。",
      },
      {
        title: "AI 產生分級",
        description: "用 ChatGPT 根據需求明確度、時程、金額線索與對方角色產生 A/B/C 優先級。",
        tools: ["chatgpt"],
        qualityGate: "AI 只提供建議，不自動覆蓋人工修改後的優先級。",
      },
      {
        title: "補上追蹤日期",
        description: "依照優先級自動填入建議追蹤日期，A 級當天處理，B 級 2 天內，C 級進入週檢查。",
        tools: ["google-sheets"],
        qualityGate: "沒有日期的列要被標成需要人工確認。",
      },
      {
        title: "每週清理",
        description: "每週匯出未回覆與已成交清單，檢查分類是否真的幫助回覆速度。",
        tools: ["google-sheets", "chatgpt"],
        qualityGate: "至少追蹤回覆時間、未回覆數與成交來源三個指標。",
      },
    ],
    faq: [
      {
        question: "可以完全自動回信嗎？",
        answer: "第一版不建議。高價值詢問信應先由 AI 產生摘要與建議回覆，再由人工確認寄出。",
      },
      {
        question: "為什麼不用 CRM？",
        answer: "CRM 更完整，但 Google Sheets 較適合 MVP。等欄位、分類與成交流程穩定後再搬到 CRM。",
      },
    ],
    keywords: ["Gmail 自動整理", "Google Sheets 商機管理", "AI 詢問信分類", "n8n Gmail workflow"],
    updatedAt: "2026-06-20",
    affiliateTools: ["n8n", "make", "zapier"],
    relatedWorkflows: ["weekly-kpi-digest-from-sheets", "invoice-email-to-sheet-alert"],
  },
  {
    slug: "notion-content-calendar-ai-brief",
    title: "Notion 內容日曆產生 SEO Brief",
    summary: "把關鍵字、受眾與素材整理成可執行的內容 brief，減少每篇文章開始前的空轉。",
    category: "content-ops",
    tools: ["notion", "chatgpt", "google-sheets", "make"],
    difficulty: "intermediate",
    estimatedMinutes: 70,
    useCase: "內容團隊有很多題目，但缺少統一格式，導致每篇文章的搜尋意圖、內部連結與 CTA 都不一致。",
    steps: [
      {
        title: "建立內容資料庫",
        description: "在 Notion 建立題目、目標讀者、搜尋意圖、主要關鍵字、狀態與發布日期欄位。",
        tools: ["notion"],
        qualityGate: "每個題目都必須有搜尋意圖，不能只有模糊標題。",
      },
      {
        title: "整理關鍵字素材",
        description: "把手動研究的關鍵字、相關問題與競品觀察放入 Google Sheets，保持可追溯來源。",
        tools: ["google-sheets"],
        qualityGate: "不得把競品文章整段複製成素材，只記錄觀察與缺口。",
      },
      {
        title: "產生 brief",
        description: "用 AI 產生文章角度、段落大綱、FAQ、內部連結建議與要避開的空泛內容。",
        tools: ["chatgpt", "make"],
        qualityGate: "brief 必須包含至少一個原創案例或本方觀點。",
      },
      {
        title: "進入人工審核",
        description: "把 brief 回寫 Notion，狀態改為待審核，由編輯確認是否能進入撰寫。",
        tools: ["notion"],
        qualityGate: "沒有人工審核的 brief 不進入發布排程。",
      },
      {
        title: "回收成效",
        description: "發布後回填曝光、點擊、排名與轉換線索，讓下一批 brief 更精準。",
        tools: ["google-sheets", "notion"],
        qualityGate: "至少每 30 天回看一次低成效內容。",
      },
    ],
    faq: [
      {
        question: "這算 AI 生成垃圾內容嗎？",
        answer: "不是，只要 AI 用於整理 brief 與缺口分析，正文仍要加入真實經驗、案例與人工審核。",
      },
      {
        question: "Notion 和 Sheets 都要用嗎？",
        answer: "可以先只用 Notion。若需要統計關鍵字或成效，Sheets 會更容易排序與計算。",
      },
    ],
    keywords: ["Notion 內容日曆", "SEO brief AI", "ChatGPT 內容流程", "Make Notion 自動化"],
    updatedAt: "2026-06-18",
    affiliateTools: ["make", "notion"],
    relatedWorkflows: ["blog-outline-publishing-checklist", "weekly-kpi-digest-from-sheets"],
  },
  {
    slug: "line-support-message-triage",
    title: "LINE 客服訊息 AI 分流與人工接手提醒",
    summary: "把 LINE 訊息依緊急度、主題與風險分類，讓人工先處理退款、客訴與高價值會員。",
    category: "support-ops",
    tools: ["line", "chatgpt", "google-sheets", "n8n"],
    difficulty: "advanced",
    estimatedMinutes: 90,
    useCase: "LINE 官方帳號訊息量變大後，客服容易被重複問題淹沒，真正需要人工處理的訊息反而延遲。",
    steps: [
      {
        title: "定義訊息類型",
        description: "先列出常見類型：訂單、退款、產品問題、合作、客訴、無需回覆。",
        tools: ["google-sheets"],
        qualityGate: "每個類型都要有明確處理方式，避免分類後仍不知道下一步。",
      },
      {
        title: "串接訊息來源",
        description: "用 LINE Messaging API 或平台整合把訊息送進自動化流程。",
        tools: ["line", "n8n"],
        qualityGate: "正式上線前要確認使用者授權、隱私告知與 token 保護。",
      },
      {
        title: "AI 分類與摘要",
        description: "讓 AI 輸出主題、情緒、風險等級、建議回覆與是否需要人工接手。",
        tools: ["chatgpt"],
        qualityGate: "退款、個資、醫療法律財務類問題一律標成需要人工確認。",
      },
      {
        title: "寫入追蹤表",
        description: "把分類、摘要、處理狀態與最後回覆時間寫入 Google Sheets。",
        tools: ["google-sheets"],
        qualityGate: "同一使用者的連續訊息要能合併查看，不只看單句。",
      },
      {
        title: "建立人工提醒",
        description: "高風險或超過 SLA 的訊息送到人工工作區，避免只停在表格裡。",
        tools: ["n8n", "line"],
        qualityGate: "測試至少 10 個真實情境，確認緊急訊息會跳出提醒。",
      },
    ],
    faq: [
      {
        question: "需要先申請 LINE API 嗎？",
        answer: "如果要正式自動接收訊息，需要確認官方帳號與 Messaging API 權限；MVP 可先用匯出資料模擬。",
      },
      {
        question: "AI 可以直接回覆退款嗎？",
        answer: "不建議。退款、客訴、個資與合約相關訊息應由 AI 摘要後交給人工處理。",
      },
    ],
    keywords: ["LINE AI 客服", "LINE 訊息分流", "n8n LINE workflow", "客服自動化"],
    updatedAt: "2026-06-15",
    affiliateTools: ["n8n", "make"],
    relatedWorkflows: ["gmail-leads-to-sheets-triage", "weekly-kpi-digest-from-sheets"],
  },
  {
    slug: "weekly-kpi-digest-from-sheets",
    title: "Google Sheets 每週 KPI 摘要與異常提醒",
    summary: "把每週營運數據整理成決策摘要，讓負責人看到變化、原因假設與下週動作。",
    category: "reporting",
    tools: ["google-sheets", "chatgpt", "gmail", "zapier"],
    difficulty: "beginner",
    estimatedMinutes: 55,
    useCase: "團隊每週都有數據，但沒有人固定整理洞察，會議時間都花在找資料而不是決策。",
    steps: [
      {
        title: "整理指標表",
        description: "將流量、轉換、商機、營收、客服量等指標放進同一張週報表。",
        tools: ["google-sheets"],
        qualityGate: "每個指標都要有來源欄位，避免人工複製造成誤差。",
      },
      {
        title: "設定變化門檻",
        description: "定義週增減超過多少才算異常，例如轉換率下降 15% 或客服量增加 30%。",
        tools: ["google-sheets"],
        qualityGate: "門檻要依指標特性調整，不能全部用同一個百分比。",
      },
      {
        title: "產生摘要",
        description: "讓 AI 用固定格式整理亮點、風險、可能原因與下週建議。",
        tools: ["chatgpt"],
        qualityGate: "摘要必須引用具體數字，不接受只有形容詞的結論。",
      },
      {
        title: "寄出週報",
        description: "透過 Gmail 或自動化工具把摘要寄給負責人，附上表格連結。",
        tools: ["gmail", "zapier"],
        qualityGate: "週報寄出前保留預覽或草稿，避免錯誤數據直接發送。",
      },
      {
        title: "追蹤決策",
        description: "把會議決定的行動回寫到下一週週報，形成決策閉環。",
        tools: ["google-sheets"],
        qualityGate: "每個行動都要有負責人與下次檢查日期。",
      },
    ],
    faq: [
      {
        question: "資料還不完整可以做嗎？",
        answer: "可以，但摘要要標記資料缺口。先建立週節奏，比追求完美儀表板更重要。",
      },
      {
        question: "要用 Zapier 還是 n8n？",
        answer: "如果只是固定寄信，Zapier 上手快；若之後要串更多條件與分支，n8n 或 Make 更適合。",
      },
    ],
    keywords: ["Google Sheets KPI 摘要", "AI 週報", "Zapier Gmail 自動寄信", "營運報表自動化"],
    updatedAt: "2026-06-17",
    affiliateTools: ["zapier", "make", "n8n"],
    relatedWorkflows: ["gmail-leads-to-sheets-triage", "notion-content-calendar-ai-brief"],
  },
  {
    slug: "blog-outline-publishing-checklist",
    title: "AI 部落格大綱到發布檢查清單",
    summary: "把題目變成可發布的 SEO 檢查流程，包含內部連結、FAQ、標題與人工審核。",
    category: "content-ops",
    tools: ["chatgpt", "notion", "google-sheets"],
    difficulty: "beginner",
    estimatedMinutes: 40,
    useCase: "內容站需要穩定產出，但每篇文章品質不一致，常忘記補 FAQ、內部連結或更新日期。",
    steps: [
      {
        title: "定義文章任務",
        description: "輸入目標讀者、搜尋意圖、主要問題與希望讀者完成的動作。",
        tools: ["notion"],
        qualityGate: "不要只輸入關鍵字，必須寫清楚讀者情境。",
      },
      {
        title: "產生大綱",
        description: "用 AI 產生段落順序、FAQ、實作步驟與需要補充的第一手資訊。",
        tools: ["chatgpt"],
        qualityGate: "大綱必須有本方觀點或實測欄位，不能只有通用介紹。",
      },
      {
        title: "建立發布檢查",
        description: "把 title、description、H2、圖片 alt、內部連結、CTA 與更新日期放入檢查表。",
        tools: ["google-sheets", "notion"],
        qualityGate: "每項檢查都有完成狀態與負責人。",
      },
      {
        title: "人工補強",
        description: "補入案例、截圖、實測限制、替代方案與不適用情境。",
        tools: ["notion"],
        qualityGate: "發布前至少由一位非作者檢查是否有空泛段落。",
      },
      {
        title: "發布後更新",
        description: "每月檢查排名、點擊與跳出率，決定要補段落、改標題或合併文章。",
        tools: ["google-sheets"],
        qualityGate: "低成效內容不只重寫標題，也要檢查搜尋意圖是否錯了。",
      },
    ],
    faq: [
      {
        question: "可以用這個流程大量生成文章嗎？",
        answer: "可以支援產能，但不應自動發布大量未審核內容。品質、原創案例與更新紀錄比數量更重要。",
      },
      {
        question: "需要接 CMS 嗎？",
        answer: "第一版不需要。先用 Notion 或 Sheets 管理，等內容流程穩定後再接 CMS。",
      },
    ],
    keywords: ["AI 部落格大綱", "SEO 發布檢查清單", "ChatGPT 文章流程", "內容站自動化"],
    updatedAt: "2026-06-19",
    affiliateTools: ["notion", "chatgpt"],
    relatedWorkflows: ["notion-content-calendar-ai-brief", "weekly-kpi-digest-from-sheets"],
  },
  {
    slug: "invoice-email-to-sheet-alert",
    title: "發票與收據信件整理成付款追蹤表",
    summary: "把 Gmail 裡的發票、收據、訂閱通知整理到 Sheets，減少漏付款與漏報帳。",
    category: "reporting",
    tools: ["gmail", "google-sheets", "chatgpt", "make"],
    difficulty: "intermediate",
    estimatedMinutes: 60,
    useCase: "接案者或小公司常把發票、收據、訂閱通知散落在信箱，月底才發現缺資料。",
    steps: [
      {
        title: "定義信件來源",
        description: "用 Gmail 搜尋寄件者、關鍵字與附件類型，抓出發票、收據與訂閱扣款通知。",
        tools: ["gmail"],
        qualityGate: "排除促銷信與未付款報價單，避免誤記支出。",
      },
      {
        title: "抽取付款資訊",
        description: "擷取供應商、金額、幣別、付款日期、付款狀態與附件連結。",
        tools: ["make", "google-sheets"],
        qualityGate: "金額與幣別欄位必須可人工修正。",
      },
      {
        title: "AI 判斷類別",
        description: "用 AI 建議支出類別，例如軟體訂閱、廣告費、外包、雜支。",
        tools: ["chatgpt"],
        qualityGate: "AI 類別只是預填，正式報帳仍依會計規則確認。",
      },
      {
        title: "提醒未處理項目",
        description: "超過 7 天沒有標記已報帳或已付款的列，寄出提醒給負責人。",
        tools: ["gmail", "google-sheets"],
        qualityGate: "提醒內容要附原始信件連結與附件連結。",
      },
      {
        title: "月底封存",
        description: "每月底產生已處理與待處理清單，方便交給會計或負責人確認。",
        tools: ["google-sheets"],
        qualityGate: "封存前要檢查重複發票與缺金額資料。",
      },
    ],
    faq: [
      {
        question: "AI 可以做會計分類嗎？",
        answer: "AI 可以先做粗分類，但正式會計科目、稅務與報帳規則要由人或會計確認。",
      },
      {
        question: "附件需要自動下載嗎？",
        answer: "MVP 先保存信件與附件連結即可，等流程穩定再加檔案歸檔。",
      },
    ],
    keywords: ["Gmail 發票整理", "收據 Google Sheets", "付款追蹤自動化", "Make Gmail workflow"],
    updatedAt: "2026-06-14",
    affiliateTools: ["make", "zapier"],
    relatedWorkflows: ["gmail-leads-to-sheets-triage", "weekly-kpi-digest-from-sheets"],
  },
] as const satisfies readonly Workflow[];

export const comparisons = [
  {
    slug: "n8n-vs-make-ai-automation",
    title: "n8n vs Make：AI 自動化 MVP 該選哪一個？",
    tools: ["n8n", "make"],
    decisionMatrix: [
      {
        factor: "流程複雜度",
        winner: "n8n",
        notes: "分支、資料轉換與自架需求越多，n8n 的掌控感越好。",
      },
      {
        factor: "上手速度",
        winner: "make",
        notes: "視覺化情境與常見 SaaS 串接對非工程團隊更友善。",
      },
      {
        factor: "長期成本控制",
        winner: "n8n",
        notes: "有自架選項，但需要承擔維運、安全與備份。",
      },
      {
        factor: "行銷營運驗證",
        winner: "make",
        notes: "快速做出可展示的流程，適合先驗證是否真的省時間。",
      },
    ],
    recommendedFor: [
      "選 n8n：你有工程資源、重視自架、流程會持續變複雜。",
      "選 Make：你想快速驗證、團隊偏非技術、常用行銷與營運 SaaS。",
    ],
    updatedAt: "2026-06-21",
  },
  {
    slug: "zapier-vs-make-marketing-ops",
    title: "Zapier vs Make：行銷營運自動化怎麼選？",
    tools: ["zapier", "make"],
    decisionMatrix: [
      {
        factor: "非技術上手",
        winner: "zapier",
        notes: "短流程與主流工具整合通常最快完成。",
      },
      {
        factor: "視覺化流程",
        winner: "make",
        notes: "多分支、多模組的流程在 Make 中更容易被看懂。",
      },
      {
        factor: "成本可預測性",
        winner: "make",
        notes: "大量操作前仍需估算，但情境流程較容易拆分優化。",
      },
      {
        factor: "簡單通知與同步",
        winner: "zapier",
        notes: "如果只是表單通知、CRM 同步、寄信，Zapier 通常最省心。",
      },
    ],
    recommendedFor: [
      "選 Zapier：你只需要短流程、穩定串接、快速交付。",
      "選 Make：你需要看見完整路徑、常常調整行銷流程。",
    ],
    updatedAt: "2026-06-16",
  },
  {
    slug: "chatgpt-vs-notion-content-workflow",
    title: "ChatGPT vs Notion：內容工作流裡各自負責什麼？",
    tools: ["chatgpt", "notion"],
    decisionMatrix: [
      {
        factor: "生成與摘要",
        winner: "chatgpt",
        notes: "適合產生大綱、摘要、FAQ 與草稿檢查。",
      },
      {
        factor: "狀態管理",
        winner: "notion",
        notes: "適合保存題目、審核狀態、負責人與發布日期。",
      },
      {
        factor: "團隊協作",
        winner: "notion",
        notes: "資料庫與頁面更適合多人協作與保留決策紀錄。",
      },
      {
        factor: "快速腦暴",
        winner: "chatgpt",
        notes: "適合把模糊想法拆成角度、問題與草稿方向。",
      },
    ],
    recommendedFor: [
      "ChatGPT 當生成與檢查層，不要當唯一資料庫。",
      "Notion 當內容中台，保存審核、版本與發布狀態。",
    ],
    updatedAt: "2026-06-13",
  },
] as const satisfies readonly Comparison[];
